# renovate-debian: suite=trixie
FROM docker.io/debian:13.6-slim

# Setup image
RUN apt-get update \
    && apt-get install -y dnsmasq=2.91-1+deb13u1
# COPY config
COPY dnsmasq.conf /etc/dnsmasq.conf
# Creating directory for custom configuration and additional hosts
RUN mkdir -p /etc/dnsmasq.d /etc/dnsmasq_hosts.d
# Set custom entrypoint and command
COPY entrypoint.sh /entrypoint
EXPOSE 53/udp
EXPOSE 67/udp
VOLUME [ "/etc/dnsmasq.d", "/etc/dnsmasq_hosts.d" ]
ENTRYPOINT [ "/entrypoint" ]
CMD [ "dnsmasq" ]
