FROM docker.io/debian:12.5-slim as base

FROM base as build
# Setup image
RUN apt-get update \
    && apt-get install -y build-essential
# Download and untar dnsmasq
ARG DNSMASQ_VERSION
ADD https://dnsmasq.org/dnsmasq-${DNSMASQ_VERSION}.tar.gz /tmp/dnsmasq.tar.gz
RUN mkdir -p /tmp/dnsmasq \
    && tar -xvf /tmp/dnsmasq.tar.gz -C /tmp/dnsmasq --strip-components=1 \
    && rm /tmp/dnsmasq.tar.gz
WORKDIR /tmp/dnsmasq
# Build dnsmasq
RUN make

FROM base as dist
# Copy built dnsmasq and configuration
COPY --from=build /tmp/dnsmasq/src/dnsmasq /usr/local/sbin/dnsmasq
COPY dnsmasq.conf /etc/dnsmasq.conf
# Creating directory for custom configuration and additional hosts
RUN mkdir -p /etc/dnsmasq.d /etc/dnsmasq_hosts.d
# Set custom entrypoint and command
COPY entrypoint.sh /entrypoint
EXPOSE 53/udp
EXPOSE 67/udp
VOLUME [ "/etc/dnsmasq.d", "/etc/dnsmasq_hosts.d" ]
ENTRYPOINT [ "/entrypoint" ]
CMD [ "dnsmasq" ]
