#!/usr/bin/env sh

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# OPs are separated due to restart
systemctl enable "${MODULE_ID}.service"
systemctl restart "${MODULE_ID}.service"
