#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import agent

# open firewall for DNS and DHCP
agent.assert_exp(agent.add_public_service(os.environ['MODULE_ID'], ["53/udp", "67/udp"]))
