#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json

config = {
    "interface": "",
    "dhcp-server": {
        "enabled": False,
        "start": "",
        "end": "",
        "lease": 12
    },
    "dns-server": {
        "enabled": False,
        "primary-server": "",
        "secondary-server": ""
    },
}

open("config.json", "w").write(json.dumps(config))

open("dns-records.json", "w").write(json.dumps({"records": []}))
