#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json

config = {
    "interface": "",
    "dhcp-server": {
        "enabled": False,
        "start": "",
        "end": "",
        "lease": 1
    },
    "dns-server": {
        "enabled": False,
        "servers": [],
        "addresses": []
    },
}

open("config.json", "w").write(json.dumps(config))
