#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys

import network

interfaces = network.list_interfaces()
interfaces_names = [interface["name"] for interface in interfaces]

json.dump({
    "data": interfaces_names
}, sys.stdout)
