#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys

import network

config = json.load(open("config.json"))

if config["interface"] != "" and config["dhcp-server"]["start"] == "" and config["dhcp-server"]["end"] == "":
    interfaces = network.list_interfaces()
    interface = next(interface for interface in interfaces if interface["name"] == config["interface"])
    config["dhcp-server"]["start"] = str(interface["start"])
    config["dhcp-server"]["end"] = str(interface["end"])

json.dump(config, sys.stdout)
